### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by iVegas** [bogdan-hepting/menu_item_extras#12]
We have some scenarios where test coverage required.
Suggest your scenario in the comment bellow.

**Comment by iVegas** [comment]
- [ ] Multilevel menu items with fields rendering

**Comment by iVegas** [comment]
- [ ] Switching menu item extras configuration and affecting on the menu item edit form.

**Comment by ozin7** [comment]
- [ ] Changing is_expanded option and check if it is shown or not
