### ISSUE TITLE
Menu Item edit form display for 8.x-2.x.

### ISSUE THREAD

**Issue by ozin7** [bogdan-hepting/menu_item_extras#29]
How menu item edit form should looks?

**Comment by iVegas** [comment]
![image](https://user-images.githubusercontent.com/11544787/28355157-7616d65e-6c6b-11e7-9a14-0948323e5208.png)

**Comment by iVegas** [comment]
1st option: extend existing edit form with added fields;
2nd option: override edit form with entity edit form using default form view display;

Any other options?
