### ISSUE TITLE
The SQL storage cannot change the schema for an existing field (bundle in menu_link_content entity) with data. in          [error] Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->updateSharedTableSchema()

### ISSUE THREAD

**Issue by a-kom** [bogdan-hepting/menu_item_extras#44]
**Module version:** 8.x-2.x
**Steps to reproduce:**
* Install module.
* Run in drush command - `drush entity-updates`
* Check error message after drush command.

**Comment by iVegas** [comment]
Alpha release blocker

**Comment by a-kom** [comment]
Fixed on installation, on uninstalling the problem is the same and needs investigation.
