### ISSUE TITLE
Add road map for alpha, beta and rc releases

### ISSUE THREAD

**Issue by ozin7** [bogdan-hepting/menu_item_extras#64]

**Comment by ozin7** [comment]
**8.x-2.x-alpha**
_Done_: 
 - Base functionality implemented, Menu Link Content entity is full fieldable!!!
 - Fixed templates
 - Added view mode field which give control on view mode per item.
 - Clear data from the extra entity field like View mode
_Will be added_: 
- Update path from the 1.x to 2.x
- Demo modules which will demonstrate power of this module, and what magic you can do with it.

**8.x-2.x-beta**
_Done_ : All features from the alpha version.
_Will be added_: Test coverage based on the demo modules.

**8.x-2.x-rc**
_Done_ : All features from the beta version 
_Will be added_: 
 - Fixed all critical issues

**Comment by iVegas** [comment]
Done
