### ISSUE TITLE
User error: "menu_level" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of core/lib/Drupal/Core/Render/Element.php).

### ISSUE THREAD

**Issue by a-kom** [bogdan-hepting/menu_item_extras#74]
Try to add some fields and change order, render display and then clear cache. Check results on menu page.

**Comment by iVegas** [comment]
test required

**Comment by a-kom** [comment]
Steps for reproducing:
1) Create a menu with enabled menu extras module.
2) Add field to menu(e.g. paragraph field for render)
3) Add in menu 3 items 
4) Add for prev items children menu links.
5) Render menu in some block.
6) Flush all caches and check error.

**Comment by a-kom** [comment]
Merged, tests will be with examples module.
