### ISSUE TITLE
Moving default branch from a master to a major version branch

### ISSUE THREAD

**Issue by iVegas** [bogdan-hepting/menu_item_extras#8]
Default branch should be referenced to a major version branch.

See:
https://www.drupal.org/empty-git-master
https://www.drupal.org/node/1659588
https://help.github.com/articles/setting-the-default-branch/

**Comment by bogdan-hepting** [comment]
moved default branch to `8.x-1.x`

**Comment by iVegas** [comment]
Also, we don't need master branch anymore:
```bash
git push origin :master
```

**Comment by iVegas** [comment]
Done
