### ISSUE TITLE
Build logic for rendering item content

### ISSUE THREAD

**Issue by ozin7** [bogdan-hepting/menu_item_extras#9]
Problem:
We have next code in our template:

```
{% if item.below or item.content|render and item.is_expanded %}
          <div class="menu-level js-menu-level">

            {% if item.content|render %}
            <div class="menu-item--content-extras">
              {{ item.content }}
            </div>
            {% endif %}

            {{ menus.menu_links(item.below, attributes, menu_level + 1) }}
          </div>
 {% endif %}
```
When menu item has set show expanded to TRUE but if it does not have subitems in the template is_expanded = FALSE, so when we have item content but item does not have subitems our content is not rendered.

My suggestion here is to add one more indicator `show_content` which will check if original menu link entity has set `is_expanded` to TRUE and  content is not empty.

What yours thoughts about this?

**Comment by ozin7** [comment]
@bogdan-hepting please add description for the `content` and remove `item.is_expanded` checking.

**Comment by bogdan-hepting** [comment]
done
